name: Build and Deploy to S3

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm install

            - name: Build with Webpack
              run: npm run build

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
                  distribution-id: ${{ secrets.DISTRIBUTION_ID }}

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --delete
              env:
                  AWS_S3_BUCKET: loganschipansky.com
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  SOURCE_DIR: 'dist'

            - name: Invalidate CloudFront Cache
              if: ${{ env.DISTRIBUTION_ID != '' }}
              run: aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths "/*"
              env:
                  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
